#!/bin/sh
set -eu
memory="$(grep MemFree /proc/meminfo | awk '{print int($2 / 1024 / 1024)}')"
securify_cmd="java -Xmx${memory}G -jar /securify_jar/securify.jar -co"
cd / && python3 -m sec.scripts.pysolc /project /comp.json

$securify_cmd /comp.json
