#!/bin/sh
set -eu
memory="$(grep MemAvailable /proc/meminfo | awk '{print int($2 / 1024 / 1024)}')"
if [ "$memory" -eq 0 ]; then
  memory=1
fi
echo "Using ""$memory""G to run Securify inside the docker container."
securify_cmd="java -Xmx"$memory"G -jar /securify_jar/securify.jar -co"
cd / && python3 -m sec.scripts.pysolc /project /comp.json

$securify_cmd /comp.json
